name: 2026
on:
  schedule:
    - cron: '45 8 * * 1-5'
    # 8 个小时时差

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Display Github Actions bot username
        run: echo ${{ github.actor }} 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install setuptools
        run: python -m pip install --upgrade setuptools==56.0.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==24.0
          pip install -r requirements.txt
      - name: run
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 600
          max_attempts: 2
          command: python main.py --func all
      - name: Run Playwright script
        run: python stock/cls/stock_cls_zt_analyse.py # 替换成你的文件名
      - name: Get current date
        id: date
        run: echo "current_date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: git
        run: |
          git config --global user.email "pangyouzhen@live.com"
          git config --global user.name "pangyouzhen"
          git add .
          git commit -m "${{ steps.date.outputs.current_date }} update"
          [ $? -eq 1 ] && echo "No changes to commit." || git push
